version: "3"

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=wordcloud
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=wordcloud

  web:
    build: .
    command: ./start_web.sh
    restart: on-failure
    volumes:
      - .:/var/labhacker/wordcloud_backend
    environment:
      - SECRET_KEY=key
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_ENGINE=postgresql
      - NAME=wordcloud
      - USER=root
      - PASSWORD=wordcloud
      - HOST=db
      - PORT=5432
      - REDIS_SERVER=redis://redis:6379
      - AUDIENCIAS_API_URL=https://edemocracia.camara.leg.br/audiencias/api/question/?room__legislative_body_initials=CEXCORVI
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    command: redis-server

  celery:
    build: .
    command: bash -c "cd src && celery -A wordcloud_backend worker -l info"
    volumes:
      - .:/var/labhacker/wordcloud_backend
    environment:
      - SECRET_KEY=key
      - DEBUG=True
      - DATABASE_ENGINE=postgresql
      - NAME=wordcloud
      - USER=root
      - PASSWORD=wordcloud
      - HOST=db
      - PORT=5432
      - REDIS_SERVER=redis://redis:6379
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build: .
    command: ./start_celery_beat.sh
    volumes:
      - .:/var/labhacker/wordcloud_backend
    environment:
      - SECRET_KEY=key
      - DEBUG=True
      - DATABASE_ENGINE=postgresql
      - NAME=wordcloud
      - USER=root
      - PASSWORD=wordcloud
      - HOST=db
      - PORT=5432
      - REDIS_SERVER=redis://redis:6379
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
