version: "3"
services:
  db:
    container_name: wordcloud-db
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=wordcloud
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=wordcloud
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    container_name: wordcloud-backend
    build: .
    command: ./start_web.sh
    restart: on-failure
    volumes:
      - .:/var/labhacker/wordcloud_backend:z
    environment:
      - SECRET_KEY=key
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_ENGINE=postgresql
      - NAME=wordcloud
      - USER=root
      - PASSWORD=wordcloud
      - HOST=db
      - PORT=5432
      - REDIS_SERVER=redis://redis:6379
      - AUDIENCIAS_API_URL=https://edemocracia.camara.leg.br/audiencias/api/question/?room__legislative_body_initials=CEXCORVI
      - STATIC_URL=/api/static/
      - URL_PREFIX=api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    container_name: wordcloud-redis
    image: "redis:alpine"
    command: redis-server
  worker:
    container_name: wordcloud-worker
    image: labhackercd/wordcloud_backend:latest
    command: bash -c "cd src && celery -A wordcloud_backend worker -l info"
    volumes:
      - .:/var/labhacker/wordcloud_backend
    environment:
      - SECRET_KEY=key
      - DEBUG=True
      - DATABASE_ENGINE=postgresql
      - NAME=wordcloud
      - USER=root
      - PASSWORD=wordcloud
      - HOST=db
      - PORT=5432
      - AUDIENCIAS_API_URL=https://edemocracia.camara.leg.br/audiencias/api/question/?room__legislative_body_initials=CEXCORVI
      - REDIS_SERVER=redis://redis:6379
    depends_on:
      - db
      - redis
      - backend
  beat:
    container_name: wordcloud-beat
    image: labhackercd/wordcloud_backend:latest
    command: ./start_celery_beat.sh
    volumes:
      - .:/var/labhacker/wordcloud_backend:z
    environment:
      - SECRET_KEY=key
      - DEBUG=True
      - DATABASE_ENGINE=postgresql
      - NAME=wordcloud
      - USER=root
      - PASSWORD=wordcloud
      - HOST=db
      - PORT=5432
      - AUDIENCIAS_API_URL=https://edemocracia.camara.leg.br/audiencias/api/question/?room__legislative_body_initials=CEXCORVI
      - REDIS_SERVER=redis://redis:6379
    depends_on:
      - db
      - redis
      - backend

volumes:
  pg_data:
    driver: local
  backend:
    driver: local
  worker:
    driver: local
  beat:
    driver: local
