version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python nltk_data.py && python src/manage.py migrate --noinput && python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/var/labhacker/wordcloud_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: bash -c "cd src && celery -A wordcloud_backend worker -l info"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: bash -c "cd src && celery -A wordcloud_backend beat -l info"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
