# Generated by Django 3.0.6 on 2020-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienciasQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveIntegerField(default=0, verbose_name='room id')),
                ('question_id', models.PositiveIntegerField(default=0, verbose_name='question id')),
                ('question', models.CharField(max_length=250, verbose_name='question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
