# Generated by Django 3.0.6 on 2020-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienciasquestion',
            name='question',
            field=models.TextField(verbose_name='question'),
        ),
    ]
